# Generated by Django 4.1.2 on 2022-10-22 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entrega', models.CharField(max_length=50)),
                ('nombre_jefeLinea', models.CharField(max_length=50)),
                ('piezasAutomotriz', models.IntegerField()),
                ('piezasMicrotec', models.IntegerField()),
                ('productosAutomotrizTerminadas', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
